apiVersion: apps/v1
kind: Deployment
metadata:
  name: isig-cd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: isig-cd
  template:
    metadata:
      labels:
        app: isig-cd
    spec:
      containers:
      - image: ghcr.io/itema-as/isig:master
        name: isig-cd
        ports:
        - containerPort: 8080

