apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: cd=ghcr.io/itema-as/isig:1.0.0
  name: isig
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./argocd-applications/isig/prod
    repoURL: https://github.com/itema-as/gitops-in-practice.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true

